### ISSUE TITLE
Problems with closed Tickets

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#10]
When you close a ticket and it is marked as important. the staff will allways get informed
"There is a ticket that is markted as important"
Problem: If you have 50 Tickets in your System ..then u dont know witch of the 50 ticktes it is.
(ist not nice if u Need to check all tickets if the important flag was enabled in it)

Also you have no list or anything like this to list closed tickets.
in the normal **/mpdreq list** they got hidden after Closing....

And Last Problem coomes if you Combine the first Problem with the secound one.

The Ticket is marked as important but is closed…. and now?...
correct. the stuff got logged in seens there is a ticket that is marked as important.
but if he does /modreq list then you dont see this ticket anymore because it is closed allready..

Is there any way to Change this? :)

**Comment by SuperRonanCraft** [comment]
Btw, u can list closed tickets with "/modreq list closed" I will be adding more on this in 5.6.0
