### ISSUE TITLE
A note that just exist in the SpigotDoc :3

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#12]
New:
    Enabled: true
    Sound: BLOCK_NOTE_BASEDRUM

![image](https://user-images.githubusercontent.com/12080017/46284068-c95e1880-c576-11e8-9dbc-6072dfcda75a.png)

Looks like it does not exists...but if we take a look here:

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

well we see that the block is called now: BLOCK_NOTE_BLOCK_BASEDRUM
well i think they did this with all Noteblock sounds….

Well i remain this here, but you can close the issues now if you want. Just havent closed it Jet so you can read it.

**Comment by SuperRonanCraft** [comment]
This sound exists on 1.12.2, and I do have an error system to make the plugin not break if sounds fail. So that's that system there. I do want ti to be 1.8-1.13 friendly, so I don't know what sounds did not change since then.

**Comment by CloudeLecaw** [comment]
May you can simply add a #Information where to find the Soundnames if using 1.13 (see link above) and say that user have to Change them manually if using 1.13 or above (the new soundnames and noteblocknames are only in 1.13 and above)

**Comment by SuperRonanCraft** [comment]
Yeah, that's where the new wiki will come in handy, I'm making a huge wiki update that will be replacing the current one that is under the code tab :)

**Comment by SuperRonanCraft** [comment]
Alright, I'ma make a not on this, but I'ma close the issue as it's more a quality of life change ;)
