### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#13]
Is it possible to translate all gui messages? Like Posted by, Status, Reply, Importance, Category and others? We can translate all messages, but not the most important in gui :/

**Comment by SuperRonanCraft** [comment]
Yeah, in the **menu.yml** file u can find all the messages, nothing is hardcoded message wise :)

**Comment by Kryniowesegryderiusz** [comment]
Oh fuck, i overlooked it. Thank you <3 <3
