### ISSUE TITLE
[Request] Importance Staff System

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#16]
Well as i noticed there are 5 Ranks for choosing an importannce of a ticket.
All is fine that you can choose the importance of a cathegory but we think its no good option to let the user self choose this importance like in "others"

Well it would be nice if there would be a command for the staffmembers that let setup/change the importance of ticket can be changed.

It also would be nice f the informer would work by permission/importance.
means:

Let say the Mod is allowed to get informed (also on login) if a ticket is created of importance 2
then he can setup if it should be higher importance or not by a command.
The Admin only gets informed (also on login) the importance in 3 or 4.. depend on his permission
he also can setup if it should higher importance or not by a command.
and finaly the owner only gets informed (also on login) if the importance is 5..
if the Mod allready made it importance 5 then only the owner sees it because admin only has permission for 3 and 5.
This way you could create up to 5 Ranks that can manage who should be able to get informed.
In all cases. the author should get informed like he currently does, even if the importance is 2,3,4,5

This would allow to cathegories tickets between the staffmembers in a very nice organiced way

**Comment by SuperRonanCraft** [comment]
Well, you can force an importance on a category like the default grief category of five.

But I would agree notifications and permission based login preferences for more important tickets, I will definitely want to add this functionality. The more control the better right :P

**Comment by CloudeLecaw** [comment]
Ahh i see u made the importance of a ticket changeable <3..great work!

**Comment by SuperRonanCraft** [comment]
Yeah, not to worry, I haven't closed this issue because this is literally the addition that needed to be added to add what you want, I would like to add this without affecting permissions too much and not have too much permissions checking. I will be adding this on 5.7.2 :)

**Comment by SuperRonanCraft** [comment]
Alright, on the most recent patch I think I made a move towards this addition with current system, if you give a player permission to make importance level 1, 2 and 3, they will can only receive notification on those permissions as well, try it out and tell me if it works on the latest update ;)

**Comment by CloudeLecaw** [comment]
Hello SuperRonanCraft.

Today i made some test with the 1.8.2 Version.

i tried also to see what happens if the Groups have

    - advancedmodreq.importance.1
    - advancedmodreq.importance.2
    - advancedmodreq.importance.3
    - advancedmodreq.importance.4
    - advancedmodreq.importance.5

like needed they just can Setup an impotance of the Level.
what i now would still Need is that if a Mod set it to
importance 3: for example
that the Mod can see it
an if he dedice to make in impotance 4..for example then only the admin sees it on Login..currently it is bases on the notification permission when they Login

      advancedmodreq.notifications.player: true
      advancedmodreq.notifications.opened: true
      advancedmodreq.notifications.flagged: true
      advancedmodreq.notifications.new: true
      advancedmodreq.notifications.claimed: true


So it may now would be nice that he have the importance Level permisison + the notification that he only got informed then.. then i may could do this what i needed :3

Example: if a ticket is importance 4 and the admin  would Need

      advancedmodreq.notifications.player
      advancedmodreq.notifications.opened
      advancedmodreq.notifications.flagged
      advancedmodreq.notifications.new
      advancedmodreq.notifications.claimed
      and     - advancedmodreq.importance.4

if he would not have the importance permissions then he will not get informed.

currently it infoms him when he just has the notification permissions
