### ISSUE TITLE
[Issues] /modreq purge closed - should be - /modreq purge close

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#20]
if you try to Tabcomplet you will see 

/modreq purge [TAB]  all/open/close

Choosing close give no responce
for getting a responce/reaction you Need to use **/modreq purge closed**
the d of "closed" should be removed from this command so we can use the close that is shown in TabComplet

Testet with Verison 5.7.2
spigot: 1.13.1

**Comment by SuperRonanCraft** [comment]
You make a very good point, I'll make sure to make this change along with the new secret Signs update ;)
