### ISSUE TITLE
Bug and Question?

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#21]
Hey i tested the new CommandSign Feature in 5.8.1

when i created a sign you see:

![image](https://user-images.githubusercontent.com/12080017/47301434-2cdfe100-d61f-11e8-9653-923dabba80d9.png)
Well.. it makes sense if you see a a ticket was created with a sign with ticketnummer… but this… The command even cant be used ;).. /arm hilfe bitte...… this was the report from the sign..

Looking in the langfile…
  Signs:
    Created: '%prefix%&7Command sign has been created! &7Command is... "&f/amr %command%&7"'

...ok..what is this? Creat commands for a sign? with command shown?... well Looks like the idea came from a commandsign Plugin....

Well even if a sign is created … there is comethoing not entry.. in the database or enywhere..just the Little informal that the sign was placed..
so what this sign is for?

The next i wanne ask for is: the [amr] .. on the sign.. is it possible to Change this in the config? didnt found a place for this..

**Comment by SuperRonanCraft** [comment]
So signs are basically commands yes, really early in development and it wasy idea so I'm not too concrete on the idea yet. But I do feel it's informational enough right? It sends you a message with the command it will execute when clicked.

You can change the title of signs in the signs.yml file.
You can find out exactly what signs do in the wiki page [here](../../wiki)

**Comment by CloudeLecaw** [comment]
Currently i changed the sings.yml to [Report] but i still need to create the sign with [amr] when i have done this it automaticly chages to [Report] what i Was asking for if i can change the [amr] for creation...  Or is this an error of the early development?

**Comment by SuperRonanCraft** [comment]
Why would you need to change this? It's meant so you can create signs easily. You can also just write out the title you put in the signs.yml file, like if you put "&a[Report]" you can just write oput "&a[Report]" and wit will do the same thing

**Comment by SuperRonanCraft** [comment]
Is there something i'm missing here? Because i'm not too sure what you asking to change exactly

**Comment by CloudeLecaw** [comment]
Let me try to explain i will add some Picture so i may be easier to understand what i mean.

this is my sign.yml
```
Settings:
  Enabled: true
  Title: '&b&l[Report]'
```

I place a sign:
![image](https://user-images.githubusercontent.com/12080017/47438492-dd2e2080-d7aa-11e8-9e11-0ee470be3975.png)

When done it Looks like the Setting:
![image](https://user-images.githubusercontent.com/12080017/47438534-f1721d80-d7aa-11e8-8380-7832ca4863cd.png)

my Question is if there is a Setting where i can Change it on signcreation from current [amr] to something else like [Report]

**Comment by CloudeLecaw** [comment]
but i cant click the sign... so i have no command ececution when i click on it...

**Comment by SuperRonanCraft** [comment]
Are you right-clicking the sign?

**Comment by CloudeLecaw** [comment]
yes i tried both :3

**Comment by SuperRonanCraft** [comment]
Sorry, reopening the ticket, this is still an issue i'd like to improve upon :)

**Comment by SuperRonanCraft** [comment]
This issue seems to be fixed in the latest version, signs with invalid commands will still be executed. I've also attempted to change the way the system works, but I believe the current system is still the simplest and best way to handle it
