### ISSUE TITLE
Change Request Importance Ignores Permission

### ISSUE THREAD

**Issue by VergilPrime** [SuperRonanCraft/AdvancedModreq#22]
Users with only permission to create a certain importance level of ticket as well as to change importance of tickets can change importance from and to any level of importance.

![image](https://user-images.githubusercontent.com/1651211/47894374-be213580-de1f-11e8-8b46-0320da83b401.png)

Here you can see the permission checks happening using LuckPerms Verbose, however the importance level of the request was raised from 1 to 5 and then set back to 1. Seeing as the command sender only had permission to set permission levels up to 2, the player shouldn't have been able to set the level to 5 nor modify the level of the ticket once it was above 2.

**Comment by SuperRonanCraft** [comment]
Issue should be fixed in the most recent update ;)
