### ISSUE TITLE
A couple suggestions/improvements

### ISSUE THREAD

**Issue by Segysmundo** [SuperRonanCraft/AdvancedModreq#23]
**Request**:
I think it would be more helpful if when you typed **/modreq create** the categories menu showed up first:
![image](https://user-images.githubusercontent.com/19178945/51085447-9dd3f800-1739-11e9-88b4-8b17532d4071.png)

Followed by selecting the importance:
![image](https://user-images.githubusercontent.com/19178945/51085430-3453e980-1739-11e9-9ad5-20ce5575b0a9.png)

And finally  it would prompt you to type your message in the chat like so:
![image](https://user-images.githubusercontent.com/19178945/51076955-ad066780-169f-11e9-95aa-30a4f5056d5a.png)

Showing the categories first would give players some insight on what they can report about would help them structure their tickets in a more informative and coherent way.

Following the idea of letting players create tickets by typing them through chat, it would be a nice touch to add the same system to staff replies like so:
![image](https://user-images.githubusercontent.com/19178945/51085679-fe186900-173c-11e9-8abd-cb3b0665af7b.png)

Which after right clicking on the book would prompt them to type in the reply:
![image](https://user-images.githubusercontent.com/19178945/51085790-64ea5200-173e-11e9-8a2e-606dd77e2346.png)

---------

Checking the player's chat and taking the message he typed as a way to send the ticket would let us add signs and menus (which execute **/modreq create**) for the player which they would simply have to click once, it would let them choose a category directly and then ask them to type in the ticket message in chat, without them having to know how to use commands.

I don't own the plugin and the images were made through other means but I'm planning on acquiring it if these suggestions are added.

**Comment by SuperRonanCraft** [comment]
So as of right now, categories and importance do show up for the player, only after they wanted to create a ticket. These systems need to be enabled though.
I will try to add a more user friendly method to add replies and such with a chat system, I just want it to be supported on as many servers as possible which might have a separated chat system

**Comment by Segysmundo** [comment]
Nice to hear that.

About categories I only thought they would be useful to appear before typing the ticket so players can have a look at what they report about.

But I guess this would only work if you add the chat system? Since right now it requires you to type in the message when creating the ticket and so as you said you can’t view the categories beforehand.

**Comment by SuperRonanCraft** [comment]
I do see the pros of doing such a system. Let me see if it's possible without a total recode of the ticket creation system

**Comment by SuperRonanCraft** [comment]
Alright, so sorry for the long delay. I've been trying to get back into Minecraft modding, and I've also had to relearn my plugin o errónea the months of not working on it. I will be adding these features possibly one by one so the plugin is not changed overnight for others as well. I will defenetly want to add these features though. Again sorry ;)

**Comment by Segysmundo** [comment]
No problem man, the more time spent improving it, the better.

**Comment by SuperRonanCraft** [comment]
Alright, since the latest update posted, which is 5.9.0, I do believe this system is now implementable, I will try to work on this ticket creation method, I will most likely keep the current version. But with the option to change which creation method the admin would like to use :)
Plugin is getting pretty organized code wise, so updates should be a bit quicker now.
And again, sorry for the huge delay this time, I just don't like to reply to a ticket that just leads to further question or the ticket being closed :P

**Comment by Segysmundo** [comment]
Nice, looking forward to the updates.

**Comment by ichbinashh** [comment]
Hey! Segysmundo literally took all of the thoughts of of my brain. If you're able to implement all of these features it'd make the plugin infinitely better in my opinion.

**Comment by amnrmain** [comment]
If this is implemented I will use this plugin, I need these features.

Thank you

**Comment by SuperRonanCraft** [comment]
I do believe I made this feature a couple of months ago, just never updated this issue. Go check out the new update ;)
https://www.spigotmc.org/resources/advancedmodreq-player-ticket-management-gui-mysql-notifications.40528/
