### ISSUE TITLE
Creating tickets dont work after disabling templates

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#26]
**Plugin Version**:

5.10.4

**Describe The Bug**:

When you disable templates in config the /amr create command does nothing. 

**How To Reproduce**:

1. Disable templates
2. Type /amr create help
3. There occures nothing.

**Expected Behavior**:

**Screenshots/Error Log**:

There are no errors in console
**Additional Context**:

**Comment by SuperRonanCraft** [comment]
This might have been a bug fix at some point, But I just tested it out, it works just fine, please make sure you have an updated config file :)

**Comment by Kryniowesegryderiusz** [comment]
@SuperRonanCraft No its still not working.
Im:
1. Installing plugin
2. Changing Template.Enabled: false
3. Reloading config
4. /amr create doesnt work :/
