### ISSUE TITLE
Creating tickets STILL dont work after disabling templates

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#27]
**Plugin Version**:

5.10.5

**Describe The Bug**:

When you disable templates in config the /amr create command does nothing. 

**How To Reproduce**:

1. Installing plugin
2. Changing Template.Enabled: false
3. Reloading config
4. /amr create doesnt work :/
**Expected Behavior**:

working

**Screenshots/Error Log**:

There are no errors in console
**Additional Context**:

**Comment by SuperRonanCraft** [comment]
This has hopefully been fixed in update 5.10.6 :)
