### ISSUE TITLE
Chat Interface Bug

### ISSUE THREAD

**Issue by Pajlis** [SuperRonanCraft/AdvancedModreq#29]
**Plugin Version**:
5.11.3
Paper 1.14.4

**Describe The Bug**:
When using plugins that have a chat interface, such as "BeautyQuest" (https://www.spigotmc.org/resources/beautyquests.39255/), the chat messages are sent to chat.

If I disable/remove AdvModreq, then the message is not sent through.

**How To Reproduce**:
1.) Must have both plugins installed
2.) Create a quest
3.) Set a stage and create a dialogue
4.) Type in chat to complete dialogue stage

**Expected Behavior**:
The chat interface should not be sent in chat.
![Screen Shot 2019-12-08 at 9 08 16 PM](https://user-images.githubusercontent.com/30779255/70404245-033e7080-19ff-11ea-8548-444189ccf232.png)

**Screenshots/Error Log**:
- What's wrong -
![Screen Shot 2019-12-08 at 9 06 20 PM](https://user-images.githubusercontent.com/30779255/70404210-e99d2900-19fe-11ea-9a6f-f893d18614a2.png)

Spigot Username = Qpeety

**Comment by SuperRonanCraft** [comment]
I will continue updates on this topic in issue #31. Sorry for the long delay!

https://github.com/SuperRonanCraft/AdvancedModreq/issues/31
