### ISSUE TITLE
Dollar Signs in Ticket Messages

### ISSUE THREAD

**Issue by Seanilla** [SuperRonanCraft/AdvancedModreq#30]
**Plugin Version**:
5.12.0 (and previous versions)

**Describe The Bug**:
If somebody submits a ticket which has a dollar sign in it, the ticket cannot be properly viewed when trying to view the full message _in chat_.

**How To Reproduce**:
Type: /modreq create I lost $400 please help
Type: /modreq view <ticket # from above command>
*Click* the book in the ticket menu to see the message in chat

**Expected Behavior**:
The message should appear in chat (but it doesn't, and errors appear in the server console).

**Error Log**:
ERROR Could not pass event InventoryClickEvent to AdvancedModreq v5.12.0
INFO java.lang.IndexOutOfBoundsException: No group 4
et cetera...
(Whatever you have after the dollar sign changes the exact error)

Thank you!

**Comment by SuperRonanCraft** [comment]
Okay, I will try to reproduce this and get back to you. Sorry for the late response
