### ISSUE TITLE
Default filters of tickets

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#33]
**Plugin Version**:
5.12.4

**Request**:
Now, when you open gui with tickets they are all displayed. Then you have to go to filters and then enable open only to seeanything you have to do. Option to set filters enabled by default would be awesome. because now its really annoing to set them every time on gui open

**How/Why**:

**Additional Context**:

**Comment by SuperRonanCraft** [comment]
This was added recently in 6.0.2 ;)

**Comment by Kryniowesegryderiusz** [comment]
Not using your plugins anymore xd
