### ISSUE TITLE
Ticket messages first word is being cut off

### ISSUE THREAD

**Issue by skyman478** [SuperRonanCraft/AdvancedModreq#35]
**Plugin Version**:
5.12.5

**Describe The Bug**:
Hello, The first word of every message is being cutted off from the tickets, even on plugin in default it still happens:
Texting:
![image](https://user-images.githubusercontent.com/59271049/94817260-36f5e700-03d3-11eb-83d7-527ce02ebb5d.png)

Ticket Screen:
![image](https://user-images.githubusercontent.com/59271049/94817377-53921f00-03d3-11eb-935e-c2d784496e17.png)

My chat Plugin is UltimateChat, idk if this will interfere.

**Comment by SuperRonanCraft** [comment]
This was fixed in a recent 6.x update, please update :)
