### ISSUE TITLE
Missing placeholder for msg in discord when clsoing with extra meassage

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#36]
when u close a ticket wih /modreq close <ticketID> [message] 
and you enter a meassage behind your dont see it in discord when the ticket is in unresolved state
i tried adding     - '**Nachricht**: %ticket_closed_msg%' in the discord file in the unresolved area but it does not work,
i get the placeholder instead of the measage in discord
```
    Unresolved:
    - ~~                                                              ~~
    - '**Ticket #%ticket_id% wurde von %ticket_closer% geschlossen.**'
    - '**Nachricht**: %ticket_closed_msg%'
    - ~~         
```                                                     ~~

**Comment by SuperRonanCraft** [comment]
there will be some changes to how to mark a ticket resolved/unresolved in a future patch ;)

**Comment by CloudeLecaw** [comment]
plugin works fine so long in 1.19
