### ISSUE TITLE
Missing hover on login for admins ;3

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#38]
When ad admin logs in he sees this

![Snag_dc0e686](https://user-images.githubusercontent.com/12080017/103161266-6acc8700-47df-11eb-8186-f5d22aeb1074.png)

He can click it...
but it executes /ticket list..
we did not used this...
we use /ticket to create the reports...
where can i edit these lines?
When i click it it executed /ticket list
Problem: we use /ticket to create a ticket and so u get a responce when you click it
"Your ticket needs to have minimum 5 words"
![Snag_dce248a](https://user-images.githubusercontent.com/12080017/103161378-702ad100-47e1-11eb-96fc-249022e3491b.png)

**Comment by SuperRonanCraft** [comment]
Whoops, that might be an oversight, but try disabling the command overrides as advanced custom menu now has "ticket" as a built-in alias
 I will work on making this editable potentially

**Comment by CloudeLecaw** [comment]
Just hope you have not given up on it :3

**Comment by SuperRonanCraft** [comment]
Sorry, been in quite a hiatus lately, I will get back into this project very soon.
Thank you for reminding me!

**Comment by CloudeLecaw** [comment]
seems to work fine now
