### ISSUE TITLE
cant Reply?

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#4]
When i try to Reply to a ticket then i get just shown how to use the Reply command but i cant Reply..

![image](https://user-images.githubusercontent.com/12080017/46063660-c83f7c80-c16d-11e8-8767-9beaf4631cb1.png)

May it is causes because of the config where i have to use min. 5 Word for a report? I will test reducing the amount of needed worda today and five you a report if this solves the issues or not. 

Edit: now i tested a bit.
When i do: /modreq reply 1 for ticket 1 is sais that i replied
but uf i do: /modreq reply 1 My Reply - then this does not work and i just got informed how to use the command like seen in the Picture above.. pls fix this

**Comment by SuperRonanCraft** [comment]
I see, the command was actually forever locked as it was checking for a generic command, not an argument command

**_Will be fixed in an upcoming patch_**

**Comment by SuperRonanCraft** [comment]
fixed on 5.5.2
