### ISSUE TITLE
Player names are null after reloading the plugin (and other bugs posted to discord)

### ISSUE THREAD

**Issue by joshwenke** [SuperRonanCraft/AdvancedModreq#43]
**Plugin Version**: 6.1.3

**Describe The Bug**: Player names show up as "null" in tickets. Initially the ticket shows the player name properly, it is shown in the staff broadcast message, and the line of lore in a ticket shows the player name. However, after reloading the plugin or waiting for the sync, the player name line of lore vanishes and when clicking on the book to view the full message, the player variable is filled in as "null". I am using mySQL with a sync timer interval of 1, and have tried DownloadOnReload both true and false and the problem still happens. In mySQL, the player name and UUID are both populated just fine, so I am not sure why this is happening. Players lose tickets from their /ticket status list as well when this happens.

**How To Reproduce**:

1. Create a ticket
2. Reload the plugin
3. Player name vanishes from lore and becomes null when displayed in chat

**Expected Behavior**: Player name should be consistent. 

**Screenshots/Error Log**: There are no errors in console, on startup (AMR says enabled and nothing else), no errors when reloading nor when creating tickets.

**Additional Context**:

**Comment by joshwenke** [comment]
I also posted several other bug reports to Discord #bug-reports. Let me know if I should re-post them here.

**Comment by SuperRonanCraft** [comment]
Hey, posted this update a couple days ago, go and test it out, let me know if this keeps happening ;)
https://www.spigotmc.org/resources/advanced-mod-request.40528/update?update=420421
