### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#5]
When i click on the button for Teleporting to the Ticketcreators place, i got teleported there and the Chat tells me the following:

![image](https://user-images.githubusercontent.com/12080017/46063724-fa50de80-c16d-11e8-8562-724a8e66293c.png)

What went wrong? i got teleported to the place where the Player created the ticket... so i see Nothing that went wrong..

well i may see a the Problem in console..

`[09:15:40] [Server thread/INFO]: [0;37;22m[[0;33;22m[21mAdvancedModreq[0;37;22m] [0;31;1mLooks like the sound [0;37;1mBLOCK_NOTE_BASEDRUM [0;31;1mis not supported in Minecraft version [0;33;1m#git-Spigot-f823ac5-5cffeca (MC: 1.13.1)[m`

Looks like the setet up sounds are not uptodate with the 1.13.1 names of minecraft :3

I will try to Update the names manually today to newest 1.13.1 names and Report if this solves the issues. 

Edit:
ok it has Nothing to do with the old soundfiles:
Also on wrong command useage i get this error that something went wrong… i just get no Information what….

**Comment by SuperRonanCraft** [comment]
I have not been able to replicate this issue, might have to do with something not being cached before hand, could you tell me the exact steps from server start-up to when you get this message.

P.S: the "Something Went Wrong" message is a debug message intended as a backup message when a message is not found on the lang file.

**Comment by CloudeLecaw** [comment]
first i do is creating a testreport
/report Pls i Need Need your help
Then i choose a chthegore

now i do
/modreq list and choose the ticket

i click on the Teleporticon and got ported there

same happens if u use /modreq tp [Ticketnumber]

**Comment by SuperRonanCraft** [comment]
Ah alright, i think I know whats going on, I see that you are not using the default language file.
Under the "Teleport" file Section, only the english lang file has the correct layout, you will need to add to fix it for now, i will put out a hot fix for this soon
```
Teleport:
    Success: '%prefix%&7Teleported to ticket #%ticket_id% processed by %ticket_player%'
    Failed: '%prefix%&cError! The ticket #%ticket_id% has an invalid location!'
```
