### ISSUE TITLE
Reopend - Can take items out of Cathrgorie

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#7]
When i use /report I have a Little Problem

Then the GUi is showing where i normaly can choose the cathegorie
i thought the new SpigotVersion fixed this Problem but today i have it aggain
i am able to take out the items out of the GUI and not be able to click them :(

![image](https://user-images.githubusercontent.com/12080017/46192088-3ca72680-c2fa-11e8-8eb2-0c963eac80a9.png)

**Comment by SuperRonanCraft** [comment]
Now this is a unique issue, I've never had this happen, would you by chance **get me your config file**? It might be the cause of having the importance system disabled, but I would like to remove as many possibilities as possible :)

**Comment by CloudeLecaw** [comment]
Yes it happens all time now :(

**Comment by SuperRonanCraft** [comment]
This sounded like a life journey to find the source of the error xD
I will try my hardest to find the issue, for now I'ma leave the issue open for further investigation

**Comment by SuperRonanCraft** [comment]
@CloudeLecaw would you by chance have edited any other files, maybe added MySQL support or messed with the menu file or is absolutly everything default files?

**Comment by CloudeLecaw** [comment]
the problem was appearing in both cases sometimes
one with default files and also with modified files
i im not using the mySQL for the moment because i have no mySQL Space.

**Comment by SuperRonanCraft** [comment]
So I do believe I killed this bug with the categories revamp that I just pushed out on version [5.6.0](https://www.spigotmc.org/resources/advancedmodreq-player-ticket-management-gui-mysql-notifications.40528/updates) see if it changes this issue :)

**Comment by CloudeLecaw** [comment]
hmm Looks like i have not get this error anymore in the new 5.6.0.0 :)
